service: thekittens-crud

provider:
  name: aws
  runtime: nodejs10.x

environment: 
  DYNAMODB_KITTEN_TABLE: kittenTable

## tells serverless framework that handler.js holds these lambda functions
functions:
  create:
    handler: handler.create
    events: 
      - http:
          path: /v1/kitten
          method: post
  list:
    handler: handler.list
    events: 
      - http:
          path: /v1/kitten
          method: get
  get:
    handler: handler.get
      events: 
      - http:
          path: /v1/kitten/{name}
          method: get
  update:
    handler: handler.update
      events: 
      - http:
          path: /v1/kitten/{name}
          method: put
  delete:
    handler: handler.delete
      events: 
      - http:
          path: /v1/kitten/{name}
          method: delete